kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-replica
  labels:
      app: redis
      role: replica
spec:
  replicas: 2
  selector:
      app: redis
      role: replica
  template:
      metadata:
          labels:
              app: redis
              role: replica
      spec:
          containers:
            - name: redis-replica
              image: docker.io/lcwyo/redis-replica:v3
              ports:
                - name: redis-server
                  containerPort: 6379
