apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-php
spec:
  selector:
    matchLabels:
      app: guestbook-php
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: guestbook-php
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: docker.io/lcwyo/gb-frontend-php:v6
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9000
