kind: Service 
apiVersion: v1 
metadata:
  name: frontend-php-service
  labels:
    app: guestbook-php
    layer: backend   
spec:
  type: ClusterIP
  selector:
    app: frontend-php
  ports:
    - port: 9000
      targetPort: 9000